### ISSUE TITLE
Dynamic content in HTML is not found in created PDF

### ISSUE THREAD

**Issue by rulfox** [mddanishansari/html-to-pdf-convertor#5]
I have a Table with headers "Name" & "Age".
There are dynamic entries in the above table.

When running HTML code displays the Table with 2 entries.
When generating a pdf, the table is empty.

Below is the HTML code.

```html
<!DOCTYPE html>
<html>
   <head>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
   <body>
      <table>
         <thead>
            <tr>
               <td>Name</td>
               <td>Age</td>
            </tr>
         </thead>
         <tbody id="myTable"></tbody>
      </table>
   </body>
   <script>
      $(document).ready(function(){
        $("button").click(function(){
          $("h1, h2, p").addClass("blue");
          $("div").addClass("important");
        });
      
      
        var arra = [{name:'asin',age:50},{name:'vmj',age:80}]
        var temopHtml='';
      
        for(i=0;i<arra.length;i++){
        console.log(arra[i])
        var el = '<tr><td>'+arra[i].name+'</td><td>'+arra[i].age+'</td></tr>'
        temopHtml = temopHtml + el
        }
      
        $('#myTable').append(temopHtml);
      });
   </script>
   <style>
      .important {
      font-weight: bold;
      font-size: xx-large;
      }
      .blue {
      color: blue;
      }
   </style>
   </head>
</html>
```

**Comment by mddanishansari** [comment]
Hi @rulfox 

Sorry for the late reply. I got busy with life.

I have created a new [release 1.1.0](https://github.com/mddanishansari/html-to-pdf-convertor/releases/tag/1.1.0) through which you'll be able to generate dynamic content through JS. In your case, you might also need to add `INTERNET` permission in your `AndroidManifest.xml` since you are using external JS lib

Use below method to below enable Javascript which is disabled by default

```kotlin
htmlToPdfConvertor.setJavaScriptEnabled(true)
```

Below is the PDF generated from the HTML provided by you
[1670667969237.pdf](https://github.com/mddanishansari/html-to-pdf-convertor/files/10199920/1670667969237.pdf)

One final thing, from this release I have moved the library  to a new package and gradle dependencies `groupId` which is 
```gradle
implementation 'io.github.mddanishansari:html-to-pdf-convertor:1.1.0'
```
